//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENBmodelLibrary
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class BirthDay
    {
        [Key]
        [ForeignKey("Contact")]
        public int Id { get; set; }

        public string Name { get; set; }
        public string Birthday { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
