//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENBmodelLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContactContext : DbContext
    {
        /*
        static ContactContext()
        {
            Database.SetInitializer<ContactContext>(new ContextInitializer());
        }
        */

        public ContactContext()
            : base("name=ContactContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Telephone> Telephones { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<BirthDay> BirthDays { get; set; }
    }
}
